### PR TITLE
Utilize helpers.rangeFromLineNumber

### LINKED ISSUE #6: Figure out end column heuristically
Sublime does this automatically, might see what heuristic they are using.

### PR DESCRIPTION
**Pull request by Arcanemagus**
This function allows us to higlight the next "word" from a given column, as defined by the regex provided by the language for what a "word" is.

Fixes #6.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Before:
image

After:
image

**Comment by Arcanemagus** [comment]
@jimhester are you the one running @lintr-bot? It looks like it fully intends to spam every PR now that there is "bad R code" in the repo. There is no mention of who is behind it or how to disable it...

**Comment by Arcanemagus** [comment]
Ah ha! Looks like it, and found how to disable it here: https://github.com/jimhester/lintr#non-failing-lints

**Comment by jimhester** [comment]
Yep sorry about the spam, let me know if you are unable to disable it.

**Comment by Arcanemagus** [comment]
Looks like the environment variable worked 😉

Filed https://github.com/jimhester/lintr/issues/174 about the lack of documentation for where the comments were coming from.

**Pull request merged**
