### PR TITLE
Add super basic tests

### PR DESCRIPTION
**Pull request by SpainTrain**
* :microscope: Spec to activate package and check for activation

This is just to get the travis badge green for now.  It doesn't look great as red on the atom.io page :wink: 

Related #7 

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-lintr/8)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
That `.eslintrc` should probably be in the spec folder.

**Comment by Arcanemagus** [comment]
Also `eslint` should be added as a devDependency :wink:

**Comment by SpainTrain** [comment]
:white_check_mark:
 :white_check_mark:

**Comment by Arcanemagus** [comment]
Looks like you'll need the rest of the `eslint` config as well for it to understand babel.

**Comment by SpainTrain** [comment]
ya

**Comment by SpainTrain** [comment]
@jimhester feel free to give the final :shipit: since this is your baby =-D (or LMK if you'd rather not be bothered by reviews)

**Comment by jimhester** [comment]
Looks good, thank you for the pull request and review!

**Pull request merged**
